const ActionTypes = {
    RECEIVE_QUERY_RESULTS: 'RECEIVE_QUERY_RESULTS',
    RECEIVE_QUERY_REQUEST: 'RECEIVE_QUERY_REQUEST',
    RECEIVE_SERVER_LIST: 'RECEIVE_SERVER_LIST',
    RECEIVE_CURRENT_SERVER: 'RECEIVE_CURRENT_SERVER',
    RECEIVE_DATABASE_LIST: 'RECEIVE_DATABASE_LIST',
    RECEIVE_CURRENT_DATABASE: 'RECEIVE_CURRENT_DATABASE',
    RECEIVE_CURRENT_NAVLOCATION: 'RECEIVE_CURRENT_NAVLOCATION',
    RECEIVE_CURRENT_NAVQUERYLOCATION: 'RECEIVE_CURRENT_NAVQUERYLOCATION',
  };
  
  export default ActionTypes;