const ActionTypes = {
    RECEIVE_QUERY_RESULTS: 'RECEIVE_QUERY_RESULTS',
    RECEIVE_QUERY_REQUEST: 'RECEIVE_QUERY_REQUEST',
    RECEIVE_SERVER_LIST: 'RECEIVE_SERVER_LIST',
  };
  
  export default ActionTypes;